# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      #- run: npm test
      - run: npm run build # Ensure this script builds to the dist directory

  publish-gpr:
    needs: build
    runs-on: ubuntu-24.04 
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          #registry-url: https://npm.pkg.github.com/
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - working-directory: ./dist # Set working directory to dist
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
