# SPDX-License-Identifier: CC-BY-4.0 OR GPL-3.0-or-later
# This file is part of Network Engineering Pro

# When a release is created, this workflow will automatically format files with
# Prettier (if needed), execute tests using Node.js 20.x and 22.x on both Ubuntu
# 22.04 and 24.04, and finally, publish to npm.
#
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build/Test Webpack, Publish to npm

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  check-codeql:
    name: Check CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up GitHub CLI
        run: sudo apt-get install gh
      - name: Check CodeQL Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --workflow "CodeQL" --json conclusion --jq '.[0].conclusion' > codeql_status.txt
          CODEQL_STATUS=$(cat codeql_status.txt)
          if [[ "$CODEQL_STATUS" != "success" ]]; then
            echo "CodeQL Analysis did not succeed. Exiting..."
            exit 1
          fi

  build:
    needs: check-codeql
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        node-version: [20.x, 22.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ matrix.node-version }}
          restore-keys: |
            ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      # Linting not working properly, future debug
      #- name: Lint all JS using ESLint
      #run: npm run lint
      - name: Check all files with Prettier
        run: npx prettier --check .
      - name: Run tests using Mocha framework
        run: npm test
      - name: Build project
        run: npm run build
      - name: Copy package.json to dist directory
        run: cp package.json dist/

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: 20.x
          restore-keys: |
            20.x
      - name: Install dependencies
        run: npm ci
      - name: Set up Git user
        run: |
          git config --global user.email "github@sl.neteng.cc"
          git config --global user.name "SunDevil311"
      - name: Increment version
        run: npm version patch
      - name: Copy package.json to dist directory
        run: cp package.json dist/
      - name: Publish package
        working-directory: ./dist
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
